[project]
id = "closetai"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

[auth.external.google]
enabled = true

[auth.external.apple]
enabled = true

[storage]
enabled = true
